#!/bin/sh

echo "running the 'post-commit' script"
./node_modules/.bin/markdownlint  --ignore node_modules . --ignore docs .
# ./server/mysql-prescripts/**
# ./server/authenticate/docs/**
# ./server/comments/docs/**
# ./server/games/docs/**
# ./server/reviews/docs/**
# ./server/user/docs/**
