#!/bin/sh

echo "running the 'pre-commit' script"
./node_modules/.bin/eslint ./server 
# ./server/mysql-prescripts/**
# ./server/authenticate/docs/**
# ./server/comments/docs/**
# ./server/games/docs/**
# ./server/reviews/docs/**
# ./server/user/docs/**
# ./server/mysql-prescripts/reviews/docker-entrypoint.initdb.d/**
# ./server/mysql-prescripts/games/docker-entrypoint.initdb.d/**
# ./server/mysql-prescripts/comments/docker-entrypoint.initdb.d/**