version: '3'

services:
  front-end: 
    build: './front-end'
    container_name: front-end
    restart: unless-stopped
    ports:
      - "3006:3000"
    environment: 
      API_URL: https://gamereview.production.api.com 
      API_PORT: 8080
    depends_on:
      - user
      - games
      - reviews
      - comments   
      - authenticate     
    networks:
      - app-network 
      
  mysql_users:
    image: mysql:5.7
    container_name: mysql_users
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped    
    ports:
      - "3305:3306"               
    volumes:
      - "./server/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "users_db_data:/var/lib/mysql:rw"    
      - ./server/mysql-prescripts/user/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    environment: 
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: users_db
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"] 
    networks:
      - app-network 
   
  mysql_games:
    image: mysql:5.7
    container_name: mysql_games
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3307:3306"           
    volumes:
      - "./server/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "games_db_data:/var/lib/mysql:rw"    
      - ./server/mysql-prescripts/games/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/         
    environment:     
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: games_db
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]       
    networks:
      - app-network 

  mysql_reviews:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password   
    container_name: mysql_reviews
    restart: unless-stopped    
    ports:
      - "3308:3306"           
    volumes:
      - "./server/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "reviews_db_data:/var/lib/mysql:rw"    
      - ./server/mysql-prescripts/reviews/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/                 
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: reviews_db
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]  
    networks:
      - app-network 

  mysql_comments:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_comments
    restart: unless-stopped    
    ports:
      - "3309:3306"           
    volumes:
      - "./server/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "comments_db_data:/var/lib/mysql:rw"    
      - ./server/mysql-prescripts/comments/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/            
    environment:   
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: comments_db
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]  
    networks:
      - app-network      

  mysql_test:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password   
    container_name: mysql_test
    restart: unless-stopped    
    ports:
      - "3310:3306"           
    volumes:
      - "./server/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - ./server/mysql-prescripts/test/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/                 
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: mysql_test
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]  
    networks:
      - app-network           

  user:
    build: './server/user'
    container_name: user   
    restart: unless-stopped    
    ports:
      - "3001:3035"
    depends_on:
      - mysql_test   
      - mysql_users
      - authenticate
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: users_db
      DB_HOST: 'mysql_users'
      USER_TEST_DB_PORT: 3306
      MYSQL_DATABASE: 'mysql_test' 
      MYSQL_ROOT_PASSWORD: 'password'
      WAIT_HOSTS: mysql_users:3306
      WAIT_HOSTS: mysql_test:3306
    networks:
      - app-network       

  games:
    build: './server/games'
    container_name: games
    restart: unless-stopped    
    ports:
      - "3002:3034" 
    depends_on:
      - mysql_test   
      - mysql_games
      - authenticate          
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: games_db
      DB_HOST: 'mysql_games'
      GAMES_TEST_DB_PORT: 3306
      GAMES_TEST_DB_HOST: mysql_test
      MYSQL_DATABASE: 'mysql_test' 
      MYSQL_ROOT_PASSWORD: 'password'
      WAIT_HOSTS: mysql_games:3306
      WAIT_HOSTS: mysql_test:3306
    networks:
      - app-network 

  reviews:
    build: './server/reviews'
    container_name: reviews
    restart: unless-stopped    
    ports:
      - "3003:3033"  
    depends_on: 
      - mysql_test 
      - mysql_reviews  
      - authenticate        
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: reviews_db
      DB_HOST: 'mysql_reviews'
      REVIEWS_TEST_DB_PORT: 3306
      REVIEWS_TEST_DB_HOST: mysql_test
      MYSQL_DATABASE: 'mysql_test' 
      MYSQL_ROOT_PASSWORD: 'password'
      WAIT_HOSTS: mysql_reviews:3306
      WAIT_HOSTS: mysql_test:3306
    networks:
      - app-network       

  comments:
    build: './server/comments'
    container_name: comments   
    restart: unless-stopped    
    ports:
      - "3004:3032"
    depends_on:
      - mysql_test 
      - mysql_comments   
      - authenticate     
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: comments_db
      DB_HOST: 'mysql_comments'
      COMMENTS_TEST_DB_PORT: 3306
      COMMENTS_TEST_DB_HOST: mysql_test
      WAIT_HOSTS: mysql_comments:3306
      WAIT_HOSTS: mysql_test:3306
    networks:
      - app-network 

  authenticate:
    build: './server/authenticate'
    container_name: auth
    restart: unless-stopped    
    ports:
      - "3005:3031"
    depends_on:
      - mysql_users
      - mysql_test
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: users_db
      DB_HOST: mysql_users
      AUTH_TEST_DB_PORT: 3306
      AUTH_TEST_DB_HOST: mysql_test
      MYSQL_DATABASE: 'mysql_test' 
      MYSQL_ROOT_PASSWORD: 'password'
      WAIT_HOSTS: mysql_users:3306
      WAIT_HOSTS: mysql_test:3306  
    networks:
      - app-network       
        

  # same as
  # docker run -p 8080:8080 -v $(pwd):/etc/nginx/conf.d/default.conf default.conf
  nginx_server:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped    
    ports:
      - "8080:8080"     
    volumes:
      - ./front-end/build:/usr/share/nginx/html/ 
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - front-end
      - user
      - games
      - reviews
      - comments
      - authenticate
    networks:
      - app-network       

volumes:
  users_db_data:
  comments_db_data:
  games_db_data:
  reviews_db_data:

networks:
  app-network:
    driver: bridge 